# @file
# .travis.yml - Tests for composer-hydration Package.

language: php

## Run on container environment
sudo: false

php:
  - 7.0

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - cd $TRAVIS_BUILD_DIR/.travis/test
  - composer install

script:
  - composer run-script run-travis-test
